name: deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflow/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout main
      uses: actions/checkout@v2

    - name: Install doctl and log in
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
    
    - name: Connect to K8s cluster
      run: doctl kubernetes cluster kubeconfig save main
    
    - name: Apply K8s config files
      run: kubectl apply -f k8s && kubectl apply -f k8s-prod